### ISSUE TITLE
Include "shouldShowRequestPermissionRationale"

### ISSUE THREAD

**Issue by vladut-dascalescu** [sanukin39/UniAndroidPermission#14]
Hi sanukin39,

On request permission, it would be a lot better if you could add a field for on reject that tells the app if the user selected "Never show again" option or not. This is very good because if the user selected that, I should show another message/dialog to the user to tell him to change permission from settings (if the permission is required in order to continue), and do not try to request permission again, because nothing will happen. So, this is how I would imagine it:

UniAndroidPermission.RequestPermission (AndroidPermission.WRITE_EXTERNAL_STORAGE, () => {
    // add permit action
}, (neverShowAgain) => {
    // add not permit action
    // where neverShowAgain is 
    // boolean neverShowAgain = shouldShowRequestPermissionRationale( permission );
});

About shouldShowRequestPermissionRationale, I am not sure why, before asking the permission for the first time, is returns false, as if the user selected "Never show again". If this was not happening I whould have suggested to create a new function with only this check, like this : 

UniAndroidPermission.shouldShowRequestPermissionRationale(AndroidPermission.WRITE_EXTERNAL_STORAGE, () => {
		// can ask for permission
	   UniAndroidPermission.RequestPermission (AndroidPermission.WRITE_EXTERNAL_STORAGE, () => {
		         // add permit action
		}, () => {
			// add not permit action
		});
	}, () => {
		// can not ask for permission
});

Keep on the good work,
Thanks!

**Comment by sanukin39** [comment]
hi vladut-dascalescu,

Thank you for your advice!
I implemented it and release new binary!

Regards,
