### ISSUE TITLE
What to do with custom activity from other plugin?

### ISSUE THREAD

**Issue by STARasGAMES** [sanukin39/UniAndroidPermission#18]
Hi! 
I didnt try your plugin yet, because I using Firebase Messaging that uses their own custom activity.
Any workaround?

**Comment by SniperED007** [comment]
I have the same issue, did you solve it?

**Comment by STARasGAMES** [comment]
@SniperED007 
I just using this simple plugin
https://github.com/Over17/UnityAndroidPermissions
