### ISSUE TITLE
[Question] java jar source code

### ISSUE THREAD

**Issue by RemiLatapy** [sanukin39/UniAndroidPermission#3]
Do you agree to expose the code of the library (UniAndroidPermission/Assets/UniAndroidPermission/uniAndroidPermission.jar) ?
Thank, Rémi.

**Comment by sanukin39** [comment]
Hi RemiLatapy,

I added a AndroidStudioProject folder at root. It's for create jar file.
Thank you for pointing it out.

Sanuki.

**Comment by RemiLatapy** [comment]
Hey!
Thank a lot!
